name: Build and release Go binary
run-name: Binary is being compiled
on:
  push:
    branches:
      - 'main'
      - 'dev'
jobs:
  release:
    name: Create release binary
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: build
        env:
          BINARY_NAME: ${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          TAG: $(git rev-parse --short HEAD)
        run: |
          go build -o "${{ env.BINARY_NAME }}" -v
      - name: release
        uses: softprops/action-gh-release@v1
        with:
            files: ${{ env.BINARY_NAME }}
            tag_name: ${{ env.TAG }}